language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jo3yy/docker-react-nginx -f Dockerfile.prod .
script:
  - docker run -e CI=true jo3yy/docker-react-nginx npm run test -- --coverage
deploy:
  provider: heroku
  api_key: $API_KEY
  app: jo3yy-docker-react-nginx
  on:
    branch: main
  edge: true