FROM node:alpine AS builder
WORKDIR '/app'
COPY package.json .
COPY . .
RUN npm i && npm run build
# RUN npm run build

#placing the compiled files to nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]

# COPY --from=builder /app/build /usr/share/nginx/html